[tool.poetry]
name = "python-dc-test"
version = "0.1.0"
description = "Testing docker-compose"
authors = ["Hashinova"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
